### ISSUE TITLE
Error in CPython3.10

### ISSUE THREAD

**Issue by abersheeran** [pdm-project/pdm-pep517#52]
https://github.com/abersheeran/baize/pull/17/checks?check_run_id=3811820806

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 349, in <module>
    main()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 331, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 270, in build_editable
    return hook(wheel_directory, config_settings, metadata_directory)
  File "/tmp/pdm-build-env-ix8_99sb-shared/lib/python3.10/site-packages/pdm/pep517/api.py", line 86, in build_editable
    return Path(builder.build(wheel_directory)).name
  File "/tmp/pdm-build-env-ix8_99sb-shared/lib/python3.10/site-packages/pdm/pep517/wheel.py", line 76, in build
    self._write_metadata(zip_file)
  File "/tmp/pdm-build-env-ix8_99sb-shared/lib/python3.10/site-packages/pdm/pep517/editable.py", line 155, in _write_metadata
    return super()._write_metadata(wheel)
  File "/tmp/pdm-build-env-ix8_99sb-shared/lib/python3.10/site-packages/pdm/pep517/wheel.py", line 144, in _write_metadata
    self._write_wheel_file(f)
  File "/tmp/pdm-build-env-ix8_99sb-shared/lib/python3.10/site-packages/pdm/pep517/wheel.py", line 265, in _write_wheel_file
    tag=self.tag,
  File "/tmp/pdm-build-env-ix8_99sb-shared/lib/python3.10/site-packages/pdm/pep517/wheel.py", line 121, in tag
    assert (
AssertionError: would build wheel with unsupported tag ('cp310', 'cp310', 'linux_x86_64')
Install baize 0.11.0 failed
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pdm/builders/base.py", line 78, in log_subprocessor
    subprocess.check_call(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/hostedtoolcache/Python/3.10.0/x64/bin/python3.10', '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pep517/in_process/_in_process.py', 'build_editable', '/tmp/tmp1_wbu8wi']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pdm/core.py", line 198, in main
    return Core().main(args)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pdm/core.py", line 153, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pdm/core.py", line 148, in main
    f(options.project, options)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pdm/cli/commands/install.py", line 45, in handle
    actions.do_sync(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pdm/cli/actions.py", line 169, in do_sync
    handler.synchronize()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 372, in synchronize
    self.install_candidate(self_key)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 190, in install_candidate
    self.manager.install(can)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pdm/installers/manager.py", line 38, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pdm/models/candidates.py", line 307, in build
    self.wheel = builder.build(build_dir, metadata_directory=self._metadata_dir)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pdm/builders/editable.py", line 52, in build
    filename = self._hook.build_editable(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pep517/wrappers.py", line 257, in build_editable
    return self._call_hook('build_editable', {
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pep517/wrappers.py", line 318, in _call_hook
    self._subprocess_runner(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pdm/builders/base.py", line 235, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pdm/builders/base.py", line 86, in log_subprocessor
    raise BuildError(f"Call command {cmd} return non-zero status.")
pdm.exceptions.BuildError: Call command ['/opt/hostedtoolcache/Python/3.10.0/x64/bin/python3.10', '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pep517/in_process/_in_process.py', 'build_editable', '/tmp/tmp1_wbu8wi'] return non-zero status.
```

**Comment by frostming** [comment]
Fixed in latest pdm-pep517, should be okay if you rerun.
