### ISSUE TITLE
C extension tests broken with setuptools >= 61

### ISSUE THREAD

**Issue by mgorny** [pdm-project/pdm-pep517#81]
setuptools 61.0.0 introduced `pyproject.toml` support with some validation on top. As a result, a few tests are now failing due to `pyproject.toml` validation errors:

```pytb
$ pdm run pytest tests
========================================================= test session starts =========================================================
platform linux -- Python 3.10.4, pytest-7.1.1, pluggy-1.0.0
rootdir: /tmp/pdm-pep517, configfile: pyproject.toml
plugins: forked-1.4.0, anyio-3.5.0, xprocess-0.18.1, xdist-2.5.0, pkgcore-0.12.10
collected 67 items                                                                                                                    

tests/test_api.py .......x.FF....F.                                                                                             [ 25%]
tests/test_file_finder.py ................                                                                                      [ 49%]
tests/test_metadata.py .....................                                                                                    [ 80%]
tests/test_validator.py ...........                                                                                             [ 97%]
tests/test_wheel.py ..                                                                                                          [100%]

============================================================== FAILURES ===============================================================
_____________________________________________________ test_build_with_cextension ______________________________________________________

self = <pdm.pep517.wheel.WheelBuilder object at 0x7f7f6954f430>, wheel = <zipfile.ZipFile [closed]>

    def _build(self, wheel: zipfile.ZipFile) -> None:
        if not self.meta.build:
            return
        setup_py = self.ensure_setup_py()
        build_args = [
            sys.executable,
            str(setup_py),
            "build",
            "-b",
            str(self.location / "build"),
        ]
        try:
>           subprocess.check_call(build_args)

pdm/pep517/wheel.py:194: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

popenargs = (['/usr/bin/python3.10', '/tmp/pdm-pep517/tests/fixtures/projects/demo-cextension/setup.py', 'build', '-b', '/tmp/pdm-pep517/tests/fixtures/projects/demo-cextension/build'],)
kwargs = {}, retcode = 1
cmd = ['/usr/bin/python3.10', '/tmp/pdm-pep517/tests/fixtures/projects/demo-cextension/setup.py', 'build', '-b', '/tmp/pdm-pep517/tests/fixtures/projects/demo-cextension/build']

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.
    
        The arguments are the same as for the call function.  Example:
    
        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           subprocess.CalledProcessError: Command '['/usr/bin/python3.10', '/tmp/pdm-pep517/tests/fixtures/projects/demo-cextension/setup.py', 'build', '-b', '/tmp/pdm-pep517/tests/fixtures/projects/demo-cextension/build']' returned non-zero exit status 1.

/usr/lib/python3.10/subprocess.py:369: CalledProcessError

During handling of the above exception, another exception occurred:

tmp_path = PosixPath('/tmp/pytest-of-mgorny/pytest-1/test_build_with_cextension0')

    def test_build_with_cextension(tmp_path: Path) -> None:
        with build_fixture_project("demo-cextension"):
>           wheel_name = api.build_wheel(tmp_path.as_posix())

tests/test_api.py:173: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pdm/pep517/api.py:69: in build_wheel
    return Path(builder.build(wheel_directory)).name
pdm/pep517/wheel.py:76: in build
    self._build(zip_file)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <pdm.pep517.wheel.WheelBuilder object at 0x7f7f6954f430>, wheel = <zipfile.ZipFile [closed]>

    def _build(self, wheel: zipfile.ZipFile) -> None:
        if not self.meta.build:
            return
        setup_py = self.ensure_setup_py()
        build_args = [
            sys.executable,
            str(setup_py),
            "build",
            "-b",
            str(self.location / "build"),
        ]
        try:
            subprocess.check_call(build_args)
        except subprocess.CalledProcessError as e:
>           raise BuildError(f"Error occurs when running {build_args}:\n{e}")
E           pdm.pep517.exceptions.BuildError: Error occurs when running ['/usr/bin/python3.10', '/tmp/pdm-pep517/tests/fixtures/projects/demo-cextension/setup.py', 'build', '-b', '/tmp/pdm-pep517/tests/fixtures/projects/demo-cextension/build']:
E           Command '['/usr/bin/python3.10', '/tmp/pdm-pep517/tests/fixtures/projects/demo-cextension/setup.py', 'build', '-b', '/tmp/pdm-pep517/tests/fixtures/projects/demo-cextension/build']' returned non-zero exit status 1.

pdm/pep517/wheel.py:196: BuildError
-------------------------------------------------------- Captured stdout call ---------------------------------------------------------
 - Adding my_package/__init__.py
GIVEN VALUE:
    ""

OFFENDING RULE: 'format'

DEFINITION:
    {
        "type": "string",
        "format": "url"
    }
-------------------------------------------------------- Captured stderr call ---------------------------------------------------------
/usr/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:102: _ExperimentalProjectMetadata: Support for project metadata in `pyproject.toml` is still experimental and may be removed (or change) in future releases.
  warnings.warn(msg, _ExperimentalProjectMetadata)
For maximum compatibility please make sure to include a `scheme` prefix in your URL (e.g. 'http://'). Given value: 
configuration error: `project.urls.homepage` must be url
Traceback (most recent call last):
  File "/tmp/pdm-pep517/tests/fixtures/projects/demo-cextension/setup.py", line 29, in <module>
    setup(**setup_kwargs)
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 122, in setup
    dist.parse_config_files()
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 854, in parse_config_files
    pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
  File "/usr/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 54, in apply_configuration
    config = read_configuration(filepath, True, ignore_option_errors, dist)
  File "/usr/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 120, in read_configuration
    validate(subset, filepath)
  File "/usr/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 43, in validate
    raise error from None
ValueError: invalid pyproject.toml config: `project.urls.homepage`
__________________________________________________ test_build_with_cextension_in_src __________________________________________________

self = <pdm.pep517.wheel.WheelBuilder object at 0x7f7f695e0f40>, wheel = <zipfile.ZipFile [closed]>

    def _build(self, wheel: zipfile.ZipFile) -> None:
        if not self.meta.build:
            return
        setup_py = self.ensure_setup_py()
        build_args = [
            sys.executable,
            str(setup_py),
            "build",
            "-b",
            str(self.location / "build"),
        ]
        try:
>           subprocess.check_call(build_args)

pdm/pep517/wheel.py:194: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

popenargs = (['/usr/bin/python3.10', '/tmp/pdm-pep517/tests/fixtures/projects/demo-cextension-in-src/setup.py', 'build', '-b', '/tmp/pdm-pep517/tests/fixtures/projects/demo-cextension-in-src/build'],)
kwargs = {}, retcode = 1
cmd = ['/usr/bin/python3.10', '/tmp/pdm-pep517/tests/fixtures/projects/demo-cextension-in-src/setup.py', 'build', '-b', '/tmp/pdm-pep517/tests/fixtures/projects/demo-cextension-in-src/build']

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.
    
        The arguments are the same as for the call function.  Example:
    
        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           subprocess.CalledProcessError: Command '['/usr/bin/python3.10', '/tmp/pdm-pep517/tests/fixtures/projects/demo-cextension-in-src/setup.py', 'build', '-b', '/tmp/pdm-pep517/tests/fixtures/projects/demo-cextension-in-src/build']' returned non-zero exit status 1.

/usr/lib/python3.10/subprocess.py:369: CalledProcessError

During handling of the above exception, another exception occurred:

tmp_path = PosixPath('/tmp/pytest-of-mgorny/pytest-1/test_build_with_cextension_in_0')

    def test_build_with_cextension_in_src(tmp_path: Path) -> None:
        with build_fixture_project("demo-cextension-in-src"):
>           wheel_name = api.build_wheel(tmp_path.as_posix())

tests/test_api.py:196: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pdm/pep517/api.py:69: in build_wheel
    return Path(builder.build(wheel_directory)).name
pdm/pep517/wheel.py:76: in build
    self._build(zip_file)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <pdm.pep517.wheel.WheelBuilder object at 0x7f7f695e0f40>, wheel = <zipfile.ZipFile [closed]>

    def _build(self, wheel: zipfile.ZipFile) -> None:
        if not self.meta.build:
            return
        setup_py = self.ensure_setup_py()
        build_args = [
            sys.executable,
            str(setup_py),
            "build",
            "-b",
            str(self.location / "build"),
        ]
        try:
            subprocess.check_call(build_args)
        except subprocess.CalledProcessError as e:
>           raise BuildError(f"Error occurs when running {build_args}:\n{e}")
E           pdm.pep517.exceptions.BuildError: Error occurs when running ['/usr/bin/python3.10', '/tmp/pdm-pep517/tests/fixtures/projects/demo-cextension-in-src/setup.py', 'build', '-b', '/tmp/pdm-pep517/tests/fixtures/projects/demo-cextension-in-src/build']:
E           Command '['/usr/bin/python3.10', '/tmp/pdm-pep517/tests/fixtures/projects/demo-cextension-in-src/setup.py', 'build', '-b', '/tmp/pdm-pep517/tests/fixtures/projects/demo-cextension-in-src/build']' returned non-zero exit status 1.

pdm/pep517/wheel.py:196: BuildError
-------------------------------------------------------- Captured stdout call ---------------------------------------------------------
 - Adding my_package/__init__.py
GIVEN VALUE:
    ""

OFFENDING RULE: 'format'

DEFINITION:
    {
        "type": "string",
        "format": "url"
    }
-------------------------------------------------------- Captured stderr call ---------------------------------------------------------
/usr/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:102: _ExperimentalProjectMetadata: Support for project metadata in `pyproject.toml` is still experimental and may be removed (or change) in future releases.
  warnings.warn(msg, _ExperimentalProjectMetadata)
For maximum compatibility please make sure to include a `scheme` prefix in your URL (e.g. 'http://'). Given value: 
configuration error: `project.urls.homepage` must be url
Traceback (most recent call last):
  File "/tmp/pdm-pep517/tests/fixtures/projects/demo-cextension-in-src/setup.py", line 30, in <module>
    setup(**setup_kwargs)
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 122, in setup
    dist.parse_config_files()
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 854, in parse_config_files
    pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
  File "/usr/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 54, in apply_configuration
    config = read_configuration(filepath, True, ignore_option_errors, dist)
  File "/usr/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 120, in read_configuration
    validate(subset, filepath)
  File "/usr/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 43, in validate
    raise error from None
ValueError: invalid pyproject.toml config: `project.urls.homepage`
________________________________________________ test_build_purelib_project_with_build ________________________________________________

self = <pdm.pep517.wheel.WheelBuilder object at 0x7f7f696d8b20>, wheel = <zipfile.ZipFile [closed]>

    def _build(self, wheel: zipfile.ZipFile) -> None:
        if not self.meta.build:
            return
        setup_py = self.ensure_setup_py()
        build_args = [
            sys.executable,
            str(setup_py),
            "build",
            "-b",
            str(self.location / "build"),
        ]
        try:
>           subprocess.check_call(build_args)

pdm/pep517/wheel.py:194: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

popenargs = (['/usr/bin/python3.10', '/tmp/pdm-pep517/tests/fixtures/projects/demo-purelib-with-build/setup.py', 'build', '-b', '/tmp/pdm-pep517/tests/fixtures/projects/demo-purelib-with-build/build'],)
kwargs = {}, retcode = 1
cmd = ['/usr/bin/python3.10', '/tmp/pdm-pep517/tests/fixtures/projects/demo-purelib-with-build/setup.py', 'build', '-b', '/tmp/pdm-pep517/tests/fixtures/projects/demo-purelib-with-build/build']

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.
    
        The arguments are the same as for the call function.  Example:
    
        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           subprocess.CalledProcessError: Command '['/usr/bin/python3.10', '/tmp/pdm-pep517/tests/fixtures/projects/demo-purelib-with-build/setup.py', 'build', '-b', '/tmp/pdm-pep517/tests/fixtures/projects/demo-purelib-with-build/build']' returned non-zero exit status 1.

/usr/lib/python3.10/subprocess.py:369: CalledProcessError

During handling of the above exception, another exception occurred:

tmp_path = PosixPath('/tmp/pytest-of-mgorny/pytest-1/test_build_purelib_project_wit0')

    def test_build_purelib_project_with_build(tmp_path: Path) -> None:
        with build_fixture_project("demo-purelib-with-build"):
>           wheel_name = api.build_wheel(tmp_path.as_posix())

tests/test_api.py:306: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pdm/pep517/api.py:69: in build_wheel
    return Path(builder.build(wheel_directory)).name
pdm/pep517/wheel.py:76: in build
    self._build(zip_file)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <pdm.pep517.wheel.WheelBuilder object at 0x7f7f696d8b20>, wheel = <zipfile.ZipFile [closed]>

    def _build(self, wheel: zipfile.ZipFile) -> None:
        if not self.meta.build:
            return
        setup_py = self.ensure_setup_py()
        build_args = [
            sys.executable,
            str(setup_py),
            "build",
            "-b",
            str(self.location / "build"),
        ]
        try:
            subprocess.check_call(build_args)
        except subprocess.CalledProcessError as e:
>           raise BuildError(f"Error occurs when running {build_args}:\n{e}")
E           pdm.pep517.exceptions.BuildError: Error occurs when running ['/usr/bin/python3.10', '/tmp/pdm-pep517/tests/fixtures/projects/demo-purelib-with-build/setup.py', 'build', '-b', '/tmp/pdm-pep517/tests/fixtures/projects/demo-purelib-with-build/build']:
E           Command '['/usr/bin/python3.10', '/tmp/pdm-pep517/tests/fixtures/projects/demo-purelib-with-build/setup.py', 'build', '-b', '/tmp/pdm-pep517/tests/fixtures/projects/demo-purelib-with-build/build']' returned non-zero exit status 1.

pdm/pep517/wheel.py:196: BuildError
-------------------------------------------------------- Captured stdout call ---------------------------------------------------------
 - Adding my_package/__init__.py
GIVEN VALUE:
    ""

OFFENDING RULE: 'format'

DEFINITION:
    {
        "type": "string",
        "format": "url"
    }
-------------------------------------------------------- Captured stderr call ---------------------------------------------------------
/usr/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:102: _ExperimentalProjectMetadata: Support for project metadata in `pyproject.toml` is still experimental and may be removed (or change) in future releases.
  warnings.warn(msg, _ExperimentalProjectMetadata)
For maximum compatibility please make sure to include a `scheme` prefix in your URL (e.g. 'http://'). Given value: 
configuration error: `project.urls.homepage` must be url
Traceback (most recent call last):
  File "/tmp/pdm-pep517/tests/fixtures/projects/demo-purelib-with-build/setup.py", line 29, in <module>
    setup(**setup_kwargs)
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 122, in setup
    dist.parse_config_files()
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 854, in parse_config_files
    pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
  File "/usr/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 54, in apply_configuration
    config = read_configuration(filepath, True, ignore_option_errors, dist)
  File "/usr/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 120, in read_configuration
    validate(subset, filepath)
  File "/usr/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 43, in validate
    raise error from None
ValueError: invalid pyproject.toml config: `project.urls.homepage`
======================================================= short test summary info =======================================================
FAILED tests/test_api.py::test_build_with_cextension - pdm.pep517.exceptions.BuildError: Error occurs when running ['/usr/bin/python...
FAILED tests/test_api.py::test_build_with_cextension_in_src - pdm.pep517.exceptions.BuildError: Error occurs when running ['/usr/bin...
FAILED tests/test_api.py::test_build_purelib_project_with_build - pdm.pep517.exceptions.BuildError: Error occurs when running ['/usr...
=============================================== 3 failed, 63 passed, 1 xfailed in 7.85s ===============================================
pytest-xprocess reminder::Be sure to terminate the started process by running 'pytest --xkill' if you have not explicitly done so in your fixture with 'xprocess.getinfo(<process_name>).terminate()'.
```

**Comment by mgorny** [comment]
I've tried fixing it by making the homepage non-null but this causes yet another validation failure:

```pytb
configuration error: `project` must not contain {'license-expression'} properties
```

I'm going to file a "sister bug" in setuptools.

**Comment by frostming** [comment]
IMO setuptools shouldn't do validation if the build backend isn't setuptools.

**Comment by mgorny** [comment]
Not sure. According to [PEP 621](https://peps.python.org/pep-0621/#table-name):

> No tools may add fields to this table which are not defined by this PEP or subsequent PEPs. For tools wishing to store their own settings in pyproject.toml, they may use the [tool] table as defined in [PEP 518](https://peps.python.org/pep-0518).

**Comment by mgorny** [comment]
That said, it's just my opinion and I'm not involved in setuptools upstream.

**Comment by frostming** [comment]
`license-expression` is specified in [PEP 639](https://www.python.org/dev/peps/pep-0639/)

**Comment by mgorny** [comment]
> `license-expression` is specified in [PEP 639](https://www.python.org/dev/peps/pep-0639/)

FWICS that's still a draft.
