### ISSUE TITLE
PEP621 ValidationError on entry-points

### ISSUE THREAD

**Issue by apollo13** [pdm-project/pdm-pep517#84]
Hi,

I am trying to convert an entrypoint like this:
https://github.com/cockroachdb/sqlalchemy-cockroachdb/blob/master/setup.py#L41-L46

to pdm:
```
[project.entry-points.sqlalchemy.dialects]
cockroachdb = "sqlalchemy_cockroachdb.psycopg2:CockroachDBDialect_psycopg2"
```

Building this fails horribly with:
```
Successfully installed pdm-pep517-0.12.3
Traceback (most recent call last):
  File "/home/florian/.local/pipx/venvs/pdm/lib64/python3.10/site-packages/pep517/in_process/_in_process.py", line 363, in <module>
    main()
  File "/home/florian/.local/pipx/venvs/pdm/lib64/python3.10/site-packages/pep517/in_process/_in_process.py", line 345, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/home/florian/.local/pipx/venvs/pdm/lib64/python3.10/site-packages/pep517/in_process/_in_process.py", line 314, in build_sdist
    return backend.build_sdist(sdist_directory, config_settings)
  File "/tmp/pdm-build-env-xdmskv1l-shared/lib/python3.8/site-packages/pdm/pep517/api.py", line 77, in build_sdist
    return Path(builder.build(sdist_directory)).name
  File "/tmp/pdm-build-env-xdmskv1l-shared/lib/python3.8/site-packages/pdm/pep517/sdist.py", line 60, in build
    version = self.meta_version
  File "/tmp/pdm-build-env-xdmskv1l-shared/lib/python3.8/site-packages/pdm/pep517/base.py", line 149, in meta_version
    meta_version = self.meta.version
  File "/tmp/pdm-build-env-xdmskv1l-shared/lib/python3.8/site-packages/pdm/pep517/base.py", line 144, in meta
    self._meta.validate(True)
  File "/tmp/pdm-build-env-xdmskv1l-shared/lib/python3.8/site-packages/pdm/pep517/metadata.py", line 87, in validate
    return validate_pep621(self._metadata, raising)
  File "/tmp/pdm-build-env-xdmskv1l-shared/lib/python3.8/site-packages/pdm/pep517/validator.py", line 85, in validate_pep621
    raise PEP621ValidationError(validator.errors)
pdm.pep517.exceptions.PEP621ValidationError: {'entry-points': [{'sqlalchemy': [{'dialects': ['must be of string type']}]}]}
```

I wonder if pdm splits the entrypoints to eagerly here.

**Comment by apollo13** [comment]
The correct syntax is:
```
[project.entry-points."sqlalchemy.dialects"]
```

Sorry for the noise.
